### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by damian-grasso** [ttm/mass#1]
When loading the music library in a script, this error returns. 

**Environment:** Ubuntu 20.04
**Python Version: 3.8**

Steps to reproduce: 
1. Write the following script and save it to test.py

import rtmidi
import music

midiOut = MidiOut()
midiOut.note(C4, 0, 1000, 127, 0)

2. Run pip install python-rtmidi, pip install music, pip install cython

3. Run python3 test.py

The following results are returned...

[Screenshot]

**Comment by damian-grasso** [comment]
![Uploading Screenshot from 2021-09-27 09-03-05.png…]()

**Comment by ttm** [comment]
this seems to regard an old and solved bug found when using the `music` package with python 3.X. Thus regardign the `music` package, not the MASS framework.
